alias vdestroy="vagrant destroy"
alias vglobal-status="vagrant global-status"
alias vhalt="vagrant halt"
alias vprovision="vagrant provision"
alias vreload="vagrant reload"
alias vssh="vagrant ssh"
alias vstatus="vagrant status"
alias vup="vagrant up"
